### ISSUE TITLE
unable to run install uild

### ISSUE THREAD

**Issue by dshingate** [aws-samples/aws-service-control-policies-deployment#2]
using windows 10 machine with vscode
after installing npm this si what i get

node_modules/@aws-cdk/assert/lib/expect.d.ts:1:22 - error TS2307: Cannot find module 'aws-cdk-lib' or its corresponding type declarations.

1 import * as cdk from 'aws-cdk-lib';
                       ~~~~~~~~~~~~~

node_modules/@aws-cdk/assert/lib/expect.d.ts:2:22 - error TS2307: Cannot find module 'aws-cdk-lib/cx-api' or its corresponding type declarations.

2 import * as api from 'aws-cdk-lib/cx-api';
                       ~~~~~~~~~~~~~~~~~~~~

node_modules/@aws-cdk/assert/lib/inspector.d.ts:1:22 - error TS2307: Cannot find module 'aws-cdk-lib/cx-api' or its 
corresponding type declarations.

1 import * as api from 'aws-cdk-lib/cx-api';
                       ~~~~~~~~~~~~~~~~~~~~

node_modules/@aws-cdk/assert/lib/synth-utils.d.ts:1:23 - error TS2307: Cannot find module 'aws-cdk-lib' or its corresponding type declarations.

1 import * as core from 'aws-cdk-lib';
                        ~~~~~~~~~~~~~

node_modules/@aws-cdk/assert/lib/synth-utils.d.ts:2:24 - error TS2307: Cannot find module 'aws-cdk-lib/cx-api' or its corresponding type declarations.

2 import * as cxapi from 'aws-cdk-lib/cx-api';
                         ~~~~~~~~~~~~~~~~~~~~

Found 5 errors in 3 files.

Errors  Files
     2  node_modules/@aws-cdk/assert/lib/expect.d.ts:1
     1  node_modules/@aws-cdk/assert/lib/inspector.d.ts:1
     2  node_modules/@aws-cdk/assert/lib/synth-utils.d.ts:1
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! aws-service-control-policies-deployment@1.0.0 build: `tsc`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the aws-service-control-policies-deployment@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

output of npm ls"
npm ERR! peer dep missing: aws-cdk-lib@^2.18.0, required by @aws-cdk/assert@2.18.0
npm ERR! peer dep missing: constructs@^10.0.0, required by @aws-cdk/assert@2.18.0

**Comment by smuralee** [comment]
Please share below details

- CDK version installed on the system - `cdk --version`
- Node and npm version installed on the system - `node -v` and `npm -v`
- Sequence of commands executed after cloning the repository

**Comment by smuralee** [comment]
@dshingate  Based on our discussion, the issue was due to incorrect installation and conflict between CDKv1 and CDKv2 which you have resolved in your environment.  Marking this as an invalid issue
