### ISSUE TITLE
Getting error while install build

### ISSUE THREAD

**Issue by dshingate** [aws-samples/aws-service-control-policies-deployment#3]
Hi Team,

I am getting below error,

> aws-service-control-policies-deployment@1.0.0 build
> tsc

test/aws-service-control-policies-deployment.test.ts:15:40 - error TS2345: Argument of type 'SetupOrgManagementStack' is not assignable to parameter of type 'Stack'.
  The types of 'tags.renderedTags.resolve' are incompatible between these types.
    Type '(context: import("C:/Users/dshingate/aws-service-control-policies-deployment/node_modules/@aws-cdk/core/lib/resolvable").IResolveContext) => any' is not assignable to type '(context: import("C:/Users/dshingate/aws-service-control-policies-deployment/node_modules/aws-cdk-lib/core/lib/resolvable").IResolveContext) => any'.
      Types of parameters 'context' and 'context' are incompatible.
        Type 'import("C:/Users/dshingate/aws-service-control-policies-deployment/node_modules/aws-cdk-lib/core/lib/resolvable").IResolveContext' is not assignable to type 'import("C:/Users/dshingate/aws-service-control-policies-deployment/node_modules/@aws-cdk/core/lib/resolvable").IResolveContext'.
          The types of 'scope.node' are incompatible between these types.
            Type 'Node' is missing the following properties from type 'ConstructNode': _actualNode, uniqueId, metadataEntry, addInfo, and 3 more.

15     expect(SynthUtils.toCloudFormation(stack)).toMatchSnapshot();
                                          ~~~~~

test/aws-service-control-policies-deployment.test.ts:23:40 - error TS2345: Argument of type 'SetupBuilderAccountStack' is not assignable to parameter of type 'Stack'.
  Types of property 'tags' are incompatible.
    Type 'import("C:/Users/dshingate/aws-service-control-policies-deployment/node_modules/@aws-cdk/core/lib/tag-manager").TagManager' is not assignable to type 'import("C:/Users/dshingate/aws-service-control-policies-deployment/node_modules/aws-cdk-lib/core/lib/tag-manager").TagManager'.

23     expect(SynthUtils.toCloudFormation(stack)).toMatchSnapshot();
                                          ~~~~~

test/aws-service-control-policies-deployment.test.ts:31:40 - error TS2345: Argument of type 'SetupMemberAccountStack' is not assignable to parameter of type 'Stack'.
  Types of property 'tags' are incompatible.
    Type 'import("C:/Users/dshingate/aws-service-control-policies-deployment/node_modules/@aws-cdk/core/lib/tag-manager").TagManager' is not assignable to type 'import("C:/Users/dshingate/aws-service-control-policies-deployment/node_modules/aws-cdk-lib/core/lib/tag-manager").TagManager'.

31     expect(SynthUtils.toCloudFormation(stack)).toMatchSnapshot();
                                          ~~~~~
Found 3 errors in the same file, starting at: test/aws-service-control-policies-deployment.test.ts:15

Below are the versions 
npm -v
8.5.5
node -v
v16.15.0

**Comment by smuralee** [comment]
The issue was due to the package.json `devDependencies` using aws-cdk version of 2.25 and dependencies having version 1.157.0. This is fixed

```
> aws-service-control-policies-deployment@1.0.0 build
> tsc

> aws-service-control-policies-deployment@1.0.0 test
> jest

 PASS  test/aws-service-control-policies-deployment.test.ts (5.123 s)
  ✓ Assumable role created in OrgManagement (67 ms)
  ✓ SCPs for the OUs created and attached in Builder (206 ms)
  ✓ Behave acceptance tests to verify the SCPs from the member account (46 ms)

Test Suites: 1 passed, 1 total
Tests:       3 passed, 3 total
Snapshots:   3 passed, 3 total
Time:        5.284 s
Ran all test suites.
```
